global:
  scrape_interval:     15s # Default scrape interval

scrape_configs:
  - job_name: 'prometheus' # Job to scrape prometheus metrics
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'mancala-actuator'
    metrics_path: '/actuator/prometheus' # Job to scrape api application metrics
    scrape_interval: 5s
    static_configs:
      - targets: ['mancala-api-1:8082', 'mancala-api-2:8082']