spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 122806740996-lcbgqqgakl7ahif3hei0ulfc7nfsf14v.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: https://localhost/login/oauth2/code/google
          facebook:
            client-id: 3228288284164239
            client-secret: dad2186dfff7bc002821c939ad0a0dbb
            redirect-uri: https://localhost/login/oauth2/code/facebook
  application:
    name: gateway
  redis:
    host: ${SPRING_REDIS_HOST:localhost}
    port: ${SPRING_REDIS_PORT:6379}
  web:
    resources:
      static-locations[0]: file:src/main/resources/static/
      static-locations[1]: classpath:/static/
  cloud:
    gateway:
      routes:
        - id: mancala-api
          uri: lb://mancala-api
          predicates:
            - Path=/**
          filters:
            - name: RequestRateLimiter
              args:
                key-resolver: '#{@userKeyResolver}'
                redis-rate-limiter.replenishRate: ${SPRING_REDIS_REPLENISH_RATE:25}
                redis-rate-limiter.burstCapacity: ${SPRING_REDIS_BURST_CAPACITY:30}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    healthcheck:
      enabled: true
  instance:
    prefer-ip-address: true

server:
  port: 443
  ssl:
    enabled: true
  ssl.key-store-type: PKCS12
  ssl.key-store: classpath:keystore/applications.p12
  ssl.key-store-password: 123456
  ssl.key-alias: applications
